---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cma-observability
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-sidecar
  namespace: cma-observability
  labels:
    thanos-store-api: "true"
spec:
  selector:
    app: prometheus
  ports:
    - port: 10901
      targetPort: 10901
      name: grpc
    - port: 10902
      targetPort: 10902
      name: http
  type: ClusterIP

# Made with Bob
