---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: cma-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cma-observability-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: cma-observability

# Made with Bob
