apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: costmanagementmetricsconfigs.costmanagement-metrics-cfg.openshift.io
spec:
  group: costmanagement-metrics-cfg.openshift.io
  names:
    kind: CostManagementMetricsConfig
    listKind: CostManagementMetricsConfigList
    plural: costmanagementmetricsconfigs
    singular: costmanagementmetricsconfig
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}

# Made with Bob
